# Generated by Django 3.2.6 on 2021-08-10 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=5000)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('price', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manager', models.CharField(max_length=200)),
                ('name_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Director'), ('m', 'Manager')], max_length=1)),
                ('name_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('name_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Director'), ('m', 'Manager')], max_length=1)),
                ('name_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('name_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, choices=[('l', 'letter'), ('c', 'call')], max_length=1)),
                ('descrip_connection', models.TextField(max_length=5000)),
                ('mark', models.CharField(blank=True, choices=[('l', 'like'), ('d', 'dislike')], max_length=1)),
                ('name_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
