# Generated by Django 3.2.6 on 2021-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_company_connection_contactemail_contactphones_manager_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name_company']},
        ),
        migrations.AddField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
