# Generated by Django 3.2.6 on 2021-08-19 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210819_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='connection',
            name='descrip_connection',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
    ]
